import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const publicDir = path.resolve(here, "../public");

test("client selectors match the HTML and preserve Alpha UX constraints", async () => {
  const [html, javascript, warmup, baseCss, themeCss] = await Promise.all([
    readFile(path.join(publicDir, "index.html"), "utf8"),
    readFile(path.join(publicDir, "app.js"), "utf8"),
    readFile(path.join(publicDir, "boot-warmup.js"), "utf8"),
    readFile(path.join(publicDir, "styles.css"), "utf8"),
    readFile(path.join(publicDir, "theme-pack-v2.css"), "utf8"),
  ]);
  const css = `${baseCss}\n${themeCss}`;

  const selectorIds = [...javascript.matchAll(/querySelector\("#([^"]+)"\)/g)].map((match) => match[1]);
  for (const id of selectorIds) {
    assert.match(html, new RegExp(`id=["']${id}["']`), `Missing #${id} in index.html`);
  }

  assert.doesNotMatch(html, /skip remaining backs/i);
  assert.doesNotMatch(html, /\benergy\b/i);
  assert.doesNotMatch(html, /פתחו חבילה כדי להתחיל|חבילת בונוס/);
  assert.match(javascript, /קלף בונוס/);
  assert.match(javascript, /הקלף הבא ייספר/);
  assert.match(css, /prefers-reduced-motion/);
  assert.match(css, /--pip/);
  assert.match(html, /aria-live/);
  assert.match(javascript, /"blank", "quote", "party", "identity", "portrait"/);
  assert.match(javascript, /const delays = \[configured\.quote, configured\.party, configured\.name, configured\.portrait\]/);
  assert.doesNotMatch(javascript, /Flip for full context/);
  assert.match(javascript, /card-quote-zone/);
  assert.match(javascript, /data-fit-card-text="quote"/);
  assert.match(javascript, /data-fit-card-text="party"/);
  assert.match(javascript, /data-fit-card-text="name"/);
  assert.match(javascript, /function fitCardText/);
  assert.match(javascript, /function applyCardStage/);
  assert.match(javascript, /progressiveStage: "blank"/);
  assert.doesNotMatch(javascript, /reveal: stage === "portrait"/);
  assert.match(javascript, /binder-shared-card/);
  assert.match(javascript, /displayCardMarkup\(card, "binder"\)/);
  assert.match(javascript, /studio-shared-card/);
  assert.match(javascript, /function cardPresentation/);
  assert.match(javascript, /function quoteTrustLabel/);
  assert.match(javascript, /function partyTrustLabel/);
  assert.match(javascript, /function configureSourceLink/);
  assert.match(javascript, /displayCardMarkup\(card, "event"\)/);
  assert.match(javascript, /const presentation = cardPresentation\(card\)/);
  assert.equal((javascript.match(/class="card-face front"/g) || []).length, 1, "all surfaces must share one card renderer");
  assert.doesNotMatch(javascript, /miniCardMarkup/);
  assert.doesNotMatch(javascript, /class="mini-card"/);
  assert.doesNotMatch(javascript, /class="concept-stage"/);
  assert.match(css, /\.card-image-meta strong/);
  assert.match(css, /\.card-name-zone[^}]*background: var\(--civic\)/);
  assert.doesNotMatch(javascript, /favorite-heart/);
  assert.doesNotMatch(javascript, /card-heart-slot/);
  assert.doesNotMatch(javascript, /function syncBinderHeartTools/);
  assert.doesNotMatch(css, /\.binder-card-tools/);
  assert.match(javascript, /card-meta-mid/);
  assert.match(javascript, /card-code-tag/);
  assert.match(javascript, /frame === "fullart-v1" \? "" : `<strong aria-label=/);
  assert.match(themeCss, /card-code-tag[\s\S]{0,280}?min-width:\s*max-content/);
  assert.doesNotMatch(themeCss, /max-width:\s*64%/);
  assert.match(themeCss, /card-face\.front \.card-name-zone[\s\S]{0,220}?font-size:\s*8cqw/);
  assert.match(javascript, /isFullart && element\.dataset\.fitCardText !== "quote"/);
  assert.match(javascript, /function localDailyChallenge/);
  assert.match(javascript, /hydrateExtras\(\)\.catch/);
  assert.match(themeCss, /card-face\.front \.card-name-zone[\s\S]{0,280}?bottom:\s*25%/);
  assert.match(themeCss, /\[data-card-frame="fullart-v1"\] \.card-party-zone[\s\S]{0,200}?bottom:\s*20%/);
  assert.match(themeCss, /\[data-card-frame="fullart-v1"\] \.card-rarity-zone[\s\S]{0,200}?bottom:\s*15%/);
  assert.match(themeCss, /bottom:\s*0;\s*height:\s*15%;\s*max-height:\s*15%/);
  assert.match(javascript, /isFullart && role === "quote"/);
  assert.match(themeCss, /\[data-card-frame="fullart-v1"\] \.card-image-meta strong[\s\S]{0,120}?display:\s*none/);
  assert.doesNotMatch(themeCss, /justify-content:\s*space-evenly/);
  assert.doesNotMatch(html, /id="dialog-share"/);
  assert.match(html, /share-icon-button/);
  assert.doesNotMatch(html, /id="dialog-gift"/);
  assert.match(css, /\.binder-slot\s*\{[^}]*aspect-ratio:\s*63\s*\/\s*96/s);
  assert.match(javascript, /function toggleFavorite/);
  assert.match(javascript, /setLabels\.FAVORITES = "פייבוריטים"/);
  assert.match(javascript, /setTimeout\(startWalkout/);
  assert.match(html, /pack-wrapper-transparent\.png/);
  assert.match(html, /id="open-pack"[^>]*>פתיחת קלף/);
  assert.match(html, /id="idle-storage"/);
  assert.match(javascript, /\/api\/idle\/settle/);
  assert.match(javascript, /\/api\/idle\/seen/);
  assert.match(javascript, /function openIdleReturn/);
  assert.match(javascript, /model\.packPhase = "sealed";\s+renderPack\(\);\s+showView\("pack"\)/);
  assert.match(html, /data-nav="growth"/);
  assert.match(html, /data-nav="growth"><span aria-hidden="true">▣<\/span>/);
  assert.doesNotMatch(html, /data-nav="growth"><span aria-hidden="true">↗/);
  assert.match(javascript, /function localAchievementList/);
  assert.match(javascript, /function achievementList/);
  assert.match(javascript, /if \(model\.token\) hydrateExtras/);
  assert.match(javascript, /model\.extrasReady = true/);
  assert.doesNotMatch(javascript, /results\.every\(\(\{ status \}\) => status === "fulfilled"\)/);
  assert.match(css, /font-variant-emoji:\s*text/);
  assert.match(html, /data-nav="achievements"/);
  assert.doesNotMatch(html, /data-nav="events"/);
  assert.match(html, /data-nav="studio"/);
  assert.match(html, /Reset daily pack now/);
  assert.match(html, /id="header-debug-reset"/);
  assert.match(html, />Presentation<\/a>/);
  assert.match(html, /poc-response\/index\.html" target="_blank"/);
  assert.match(html, /Presentation Studio/);
  assert.match(html, /poc-response\/index\.html\?studio=1/);
  assert.match(html, /Run six-card guided demo/);
  assert.match(html, /id="play-studio-reveal"/);
  assert.match(html, /Expanded content studio/);
  assert.match(html, /id="delay-quote"/);
  assert.match(html, /id="studio-party-tabs"/);
  assert.match(html, /id="studio-card-grid"/);
  assert.match(html, /Copy politician · 3 images/);
  assert.match(javascript, /buildMemberWeavePrompt/);
  assert.match(javascript, /buildWeavePrompt/);
  assert.match(javascript, /data-save-studio-card/);
  assert.match(javascript, /\/api\/studio\/content/);
  assert.match(javascript, /"01 \/ 04 · quote"/);
  assert.match(javascript, /"04 \/ 04 · portrait"/);
  assert.doesNotMatch(javascript, /REVEAL_TIMING_KEY/);
  assert.match(javascript, /\/api\/bootstrap/);
  assert.match(javascript, /\/api\/home/);
  assert.match(javascript, /\/shell\.json/);
  assert.match(html, /id="home-view"[^>]*class="view active"/);
  assert.match(javascript, /HOME_CACHE_KEY/);
  assert.match(html, /boot-warmup\.js/);
  assert.doesNotMatch(warmup, /\/api\/warm/);
  assert.doesNotMatch(warmup, /\/api\/catalog/);
  assert.match(warmup, /\/api\/home/);
  assert.match(javascript, /studioKey/);
  assert.match(javascript, /x-kalpi-studio/);
  assert.match(html, /data-studio-only/);
  assert.match(html, /id="studio-release-sets"/);
  assert.match(javascript, /function populateReleaseSets/);
  assert.match(html, /חשבון הוא אופציונלי/);
  assert.match(javascript, /\/api\/studio\/config/);
  assert.match(javascript, /updateStudioCardPreview/);
  assert.match(javascript, /\["quote\.displayText", "art\.artKey"\]/);
  assert.match(javascript, /\/api\/debug\/reset-pack/);
  assert.match(javascript, /\/api\/packs\/demo/);
  assert.match(javascript, /Daily state was not changed/);
  assert.match(html, /איך נבחר התוכן/);
  assert.match(javascript, /referral_opened/);
  assert.match(javascript, /gift_preview_created/);
  assert.match(html, /id="dialog-whatsapp"/);
  assert.match(javascript, /https:\/\/wa\.me\/\?text=/);
  assert.match(html, /id="earned-badge-rail"/);
  assert.match(html, /id="open-bibi-pack"/);
  assert.doesNotMatch(html, /id="open-quiz"/);
  assert.doesNotMatch(html, /id="quiz-dialog"/);
  assert.match(javascript, /\/api\/packs\/bibi-demo/);
  assert.match(javascript, /badgeArtwork/);
  assert.doesNotMatch(javascript, /function badgeSymbol/);
  assert.match(html, /האם תגיעו לדרגת ראש הממשלה/);
  assert.match(html, /רמה 1\/5/);
  assert.match(html, /id="level-next"/);
  assert.doesNotMatch(html, /id="dialog-copies"/);
  assert.doesNotMatch(html, /id="dialog-ownership"/);
  assert.doesNotMatch(javascript, /נתון מדומה להדגמה/);
  assert.doesNotMatch(javascript, /שחקנים נוספים מחזיקים/);
  assert.match(javascript, /function displayCardMarkup/);
  assert.match(javascript, /card-copies-tag/);
  assert.match(html, /החלפות/);
  assert.match(html, /מלחמת הסיעות/);
  assert.doesNotMatch(html, /כל סדרות המיוחדים/);
  assert.match(html, /id="level-progress"/);
  assert.match(javascript, /\/api\/events\/.*\/pull/);
  assert.match(html, /id="trade-offered-set"/);
  assert.match(html, /id="trade-wanted-set"/);
  assert.match(javascript, /function partyDisplayName/);
  assert.match(javascript, /function partyRegister/);
  assert.match(javascript, /model\.gameConfig\?\.parties/);
  assert.match(javascript, /targetPartyNameHe/);
  assert.match(javascript, /function challengeRecap/);
  assert.match(javascript, /function renderChallengeRecap/);
  assert.match(javascript, /hasCrowd = leaders\.length >= 2/);
  assert.match(javascript, /recap\.hasCrowd \? `<div class="challenge-hist">/);
  assert.match(javascript, /collectorCrowd/);
  assert.match(html, /id="daily-challenge-recap"/);
  assert.match(html, /id="today-challenge-hook"/);
  assert.doesNotMatch(html, /id="today-event-hook"/);
  assert.match(html, /id="today-leader-hook"/);
  assert.match(html, /id="site-card-peeks"/);
  assert.match(html, /id="today-challenge-visual"/);
  assert.match(html, /hero-art-knesset\.png/);
  assert.match(javascript, /function renderSiteCardPeeks/);
  assert.ok(
    html.indexOf('id="site-card-peeks"') < html.indexOf('class="masthead"'),
    "background card layer must sit behind every application surface",
  );
  assert.doesNotMatch(javascript, /לא נבחר ציטוט/);
  assert.match(javascript, /if \(!text\) return ""/);
  assert.match(html, /id="player-name"/);
  assert.match(html, /id="profile-dialog"/);
  assert.match(javascript, /\/api\/profile/);
  assert.match(html, /id="shared-view"/);
  assert.match(html, /id="shared-trust"/);
  assert.match(html, /id="open-trust-legend"/);
  assert.match(html, /home-title-row/);
  assert.match(html, /id="trust-dialog"/);
  assert.doesNotMatch(html, /id="dialog-trust"/);
  assert.match(javascript, /function showSharedCard/);
  assert.match(javascript, /תצוגת שיתוף בלבד/);
  assert.match(javascript, /הקלף לא נוסף לאוסף שלכם/);
  assert.match(javascript, /גלה עוד \$\{progression\.remaining\} קלפים חדשים כדי להתקדם לרמה הבאה/);
  assert.match(html, /data-today-nav="growth"/);
  assert.doesNotMatch(html, /data-today-nav="events"/);
  assert.match(javascript, /data-trade-card/);
  assert.match(javascript, /openCardDialog\(card\.dataset\.tradeCard\)/);
  assert.match(css, /\.app-shell\.home-active \.level-strip/);
  assert.match(css, /grid-template-areas: "identity progress"/);
  assert.match(css, /grid-template-columns: minmax\(132px, auto\) minmax\(0, 1fr\)/);
  assert.match(css, /\.level-pack-icon \{ display: none/);
  assert.match(html, /class="level-reward-pack"/);
  assert.match(css, /\.level-strip[^}]*direction: rtl/);
  assert.match(css, /\.policy-dialog ol \{ padding-inline-start:/);
  assert.match(css, /\.bottom-nav button[^}]*border-inline-start:/);
  assert.match(css, /html,\s*body\s*\{[^}]*height: 100%[^}]*overflow: hidden/s);
  assert.match(css, /\.top-nav-row\s*\{[^}]*position: fixed/s);
  assert.doesNotMatch(javascript, /window\.scrollTo/);
  assert.match(html, /id="binder-pager"/);
  assert.match(html, /id="community-tabs"/);
  assert.match(html, /role="tabpanel"/);
  assert.match(html, /aria-controls="community-panel-trade"/);
  assert.match(html, /aria-current="page"/);
  assert.match(javascript, /function moveTabFocus/);
  assert.match(javascript, /button\.tabIndex = active \? 0 : -1/);
  assert.doesNotMatch(javascript, /collection-star-count" role="button"/);
  assert.doesNotMatch(javascript, /badge-medallion" role="button"/);
  assert.doesNotMatch(javascript, /textAlign = "left"/);
  assert.match(css, /4\.2cqw/);
  assert.doesNotMatch(css, /4\.2vw/);
  assert.match(javascript, /cardTitle/);
  assert.match(javascript, /cardCode/);
  assert.match(html, /card-surface-15/);
  assert.match(html, /preload="auto"/);
  assert.match(javascript, /function catalogReady/);
  assert.match(javascript, /function loadStaticCatalog/);
  assert.match(javascript, /function hydrateExtras/);
  assert.match(javascript, /Promise\.all\(jobs\.map/);
  assert.doesNotMatch(javascript, /scheduleExtrasPrefetch/);
  assert.doesNotMatch(javascript, /extrasPrefetchTimer/);
  assert.match(javascript, /\/catalog\.json/);
  assert.match(javascript, /cache: "force-cache"/);
  assert.match(javascript, /const warmedShell = window\.__kalpiWarmup\?\.shell/);
  assert.match(javascript, /const warmedCatalog = window\.__kalpiWarmup\?\.catalog/);
  assert.match(javascript, /const warmedHome = window\.__kalpiWarmup\?\.home/);
  assert.match(javascript, /const due = !timeUntil\(model\.serverState\?\.nextIdleAt\)/);
  assert.match(javascript, /jobs\.push\(\["events", \(\) => request\("\/api\/events"\)\]\)/);
  assert.match(javascript, /request\("\/api\/trades"\)/);
  assert.match(javascript, /request\("\/api\/leaderboards"\)/);
  assert.match(javascript, /hydrateExtras\(\)\.catch/);
  assert.match(javascript, /טוענים את האלבום/);
  assert.match(javascript, /searchParams\.set\("view"/);
  assert.match(javascript, /function nextCachedIdleCard/);
  assert.match(javascript, /function cachedDueCount/);
  assert.match(javascript, /function hydrateIdleQueue/);
  assert.match(javascript, /function scheduleIdleRefill/);
  assert.match(javascript, /function flushPendingIdleSeen/);
  assert.match(javascript, /PENDING_IDLE_SEEN_KEY/);
  assert.match(javascript, /function flushPendingReports/);
  assert.match(javascript, /PENDING_REPORTS_KEY/);
  assert.match(javascript, /x-idempotency-key/);
  assert.match(javascript, /cachedDueCount\(\) > 1 \? "backlog"/);
  assert.match(javascript, /cachedBufferSize < \(model\.serverState\?\.idleCapacity \|\| 8\)/);
  assert.match(javascript, /const hasMaterializedCard = model\.idleQueue\.length > 0/);
  assert.match(javascript, /playHomePackRip\(\{ holdAtEnd: !cached \}\)/);
  assert.match(javascript, /await rip\.finished/);
  assert.match(javascript, /if \(!model\.token\) await hydrateHome\(\)/);
  assert.match(warmup, /\/catalog\.json/);
  assert.match(warmup, /\/shell\.json/);
  assert.match(warmup, /window\.__kalpiWarmup/);
  assert.match(warmup, /cache: "force-cache"/);
  assert.match(warmup, /Math\.random\(\) \* 8000/);
  assert.doesNotMatch(warmup, /\/api\/warm/);
  assert.match(css, /\.binder-slot\.is-loading/);
  assert.match(css, /binder-well-wait/);
  assert.match(html, /id="achievements-empty"/);
  assert.match(html, /id="growth-empty"/);
  assert.doesNotMatch(html, /id="quiz-fail"/);
  assert.match(html, /id="level-unlocks"/);
  assert.match(html, /id="open-pending-level"/);
  assert.match(javascript, /klafi-seen-level-dialog/);
  assert.doesNotMatch(javascript, /pendingRewards\?\.length \|\|/);
  assert.doesNotMatch(html, /שעון ירושלים/);
  assert.match(html, /theme-pack-v2\.css/);
  assert.match(html, /card-surface-15/);
  assert.match(html, /id="report-dialog"/);
  assert.match(html, /דיווח על טעות בקלף/);
  assert.match(html, /id="studio-report-list"/);
  assert.match(javascript, /function hydrateStudioReports/);
  assert.match(javascript, /function applyStudioAccess/);
  assert.match(javascript, /\/api\/studio\/reports/);
  assert.match(themeCss, /\.card-dialog \.kalpi-card[^}]*width:\s*min\(370px,\s*100%\)/s);
  assert.match(themeCss, /\.new-stamp[^}]*top:\s*50%[^}]*translateY\(-50%\)/s);
  assert.doesNotMatch(themeCss, /#pack-view \.walkout-receipt\s*\{\s*display:\s*none/);
  assert.match(javascript, /הציטוט קוצר/);
  assert.match(javascript, /ממתינה לבדיקת ועדת הבחירות/);
  assert.match(html, /data-theme="pack-v2"/);
  assert.match(html, /id="visual-theme"/);
  assert.match(html, /id="visual-card-frame"/);
  assert.match(html, /id="visual-density"/);
  assert.match(html, /id="visual-quote-reveal"/);
  assert.match(html, /id="dialog-instagram"/);
  assert.match(html, /data-debug-only/);
  assert.match(javascript, /function applyVisualConfig/);
  assert.match(javascript, /function shareToInstagram/);
  assert.match(javascript, /function makeStoryImage/);
  assert.match(javascript, /function makeWhatsAppImage/);
  assert.match(javascript, /תראה מה שלפתי בקלפי!/);
  assert.match(javascript, /function paintShareCardFace/);
  assert.match(javascript, /function paintFullartShareIdentity/);
  assert.match(javascript, /SHARE_PULL_LINE/);
  assert.match(css, /#card-dialog \.dialog-close/);
  assert.match(css, /#card-dialog \.dialog-close:focus-visible/);
  assert.doesNotMatch(css, /#card-dialog \.dialog-close:focus-visible[^}]*var\(--foil\)/);
  assert.match(javascript, /\/share\/\$\{encodeURIComponent\(cardId\)\}/);
  assert.match(html, /id="share-sheet"/);
  assert.match(html, /id="binder-flip-frame"/);
  assert.ok(
    html.indexOf('id="earned-badge-rail"') < html.indexOf('id="binder-flip-frame"')
      && html.indexOf('id="binder-flip-frame"') < html.indexOf('class="binder-head"'),
    "debug full-art flip must stay visible in the binder rail, not the hidden head",
  );
  assert.match(javascript, /DEBUG_CARD_FRAME_KEY/);
  assert.match(html, /fullart-v1/);
  assert.match(javascript, /card-identity-stack/);
  assert.match(javascript, /card-rarity-zone/);
  assert.match(css, /data-card-frame="fullart-v1"/);
  assert.match(themeCss, /#app \.kalpi-card\[data-card-frame="fullart-v1"\]/);
  assert.match(css, /dialog-meta-row/);
  assert.match(javascript, /\/api\/trades\/\$\{encodeURIComponent\(tradeId\)\}\/cancel/);
  assert.match(javascript, /new ResizeObserver/);
  assert.match(javascript, /data-card-surface/);
  assert.match(themeCss, /aspect-ratio: 63 \/ 96/);
  assert.match(css, /data-quote-reveal="ink-v2"/);
  assert.match(css, /pack-quote-ink/);
  assert.doesNotMatch(javascript, /floor: 4\.5/);
  assert.doesNotMatch(html, /id="dialog-flip"/);

  const studioStart = html.indexOf('<section id="studio-view"');
  const errorStart = html.indexOf('<section id="error-view"');
  const playerHtml = `${html.slice(0, studioStart)}${html.slice(errorStart)}`;
  const playerText = playerHtml.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ");
  assert.doesNotMatch(playerText, /שלב/);
  assert.doesNotMatch(playerText, /\b(?:Today|Binder|Growth|Achievements|Events|Creator|Copy|Close|Something|Try|cards|Source)\b/);
  for (const staleCopy of ["Why it matters", "Open today’s pack", "Share this pull", "Trade preview"]) {
    assert.doesNotMatch(javascript, new RegExp(staleCopy, "i"));
  }
});
