import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const publicDir = path.resolve(here, "../public");

test("client selectors match the HTML and preserve Alpha UX constraints", async () => {
  const [html, javascript, tipsJs, warmup, baseCss, themeCss, binderShare] = await Promise.all([
    readFile(path.join(publicDir, "index.html"), "utf8"),
    readFile(path.join(publicDir, "app.js"), "utf8"),
    readFile(path.join(publicDir, "tips.js"), "utf8"),
    readFile(path.join(publicDir, "boot-warmup.js"), "utf8"),
    readFile(path.join(publicDir, "styles.css"), "utf8"),
    readFile(path.join(publicDir, "theme-pack-v2.css"), "utf8"),
    readFile(path.join(publicDir, "share/binder.html"), "utf8"),
  ]);
  const css = `${baseCss}\n${themeCss}`;

  const selectorIds = [...`${javascript}\n${tipsJs}`.matchAll(/querySelector\("#([^"]+)"\)/g)].map((match) => match[1]);
  for (const id of selectorIds) {
    assert.match(html, new RegExp(`id=["']${id}["']`), `Missing #${id} in index.html`);
  }

  assert.doesNotMatch(html, /skip remaining backs/i);
  assert.doesNotMatch(html, /\benergy\b/i);
  assert.doesNotMatch(html, /פתחו חבילה כדי להתחיל|חבילת בונוס/);
  assert.match(javascript, /קלף בונוס/);
  assert.match(javascript, /הקלף הבא ייספר/);
  assert.match(css, /prefers-reduced-motion/);
  assert.match(css, /--pip/);
  assert.match(html, /aria-live/);
  assert.match(html, /id="skip-to-main"/);
  assert.match(html, /דילוג לתוכן/);
  assert.match(html, /class="advocacy-dock"/);
  assert.match(html, /class="top-nav-row"[\s\S]*id="open-advocacy"/);
  assert.match(css, /\.advocacy-dock \{[^}]*left:\s*max\(8px/);
  assert.match(css, /\.advocacy-dock \{[^}]*padding:\s*2px 0 4px/);
  assert.match(css, /\.advocacy-dock \{[^}]*width:\s*max-content/);
  assert.match(javascript, /function layoutAdvocacyDock/);
  assert.match(css, /\.top-nav-row \{[^}]*padding:\s*0 10px calc\(15px \+ env\(safe-area-inset-bottom\)\)/);
  assert.match(html, /id="dialog-trust"/);
  assert.match(html, /aria-labelledby="card-dialog-title"/);
  assert.match(html, /aria-labelledby="report-dialog-title"/);
  assert.match(html, /aria-labelledby="level-dialog-title"/);
  assert.match(html, /aria-labelledby="profile-dialog-title"/);
  assert.match(html, /aria-labelledby="trust-dialog-title"/);
  assert.match(html, /aria-labelledby="advocacy-sponsor"/);
  assert.match(html, /id="faction-cec-note"/);
  assert.match(html, /role="list"/);
  assert.match(javascript, /function cardTrustLine/);
  assert.match(javascript, /function prefersReducedMotion/);
  assert.match(javascript, /function finishWalkoutCard/);
  assert.match(javascript, /function playerDialogOpen/);
  assert.match(javascript, /function paintCenteredLines/);
  assert.match(javascript, /חסר באוסף/);
  assert.match(javascript, /תראו מה שלפתי בקְלָפִי!/);
  assert.doesNotMatch(javascript, /תראה מה שלפתי/);
  assert.doesNotMatch(javascript, /גלה עוד \$\{progression\.remaining\}/);
  assert.doesNotMatch(html, /id="advocacy-short"[^>]*visually-hidden/);
  assert.match(javascript, /"blank", "quote", "party", "identity", "portrait"/);
  assert.match(javascript, /const delays = \[configured\.quote, configured\.party, configured\.name, configured\.portrait\]/);
  assert.doesNotMatch(javascript, /Flip for full context/);
  assert.match(javascript, /card-quote-zone/);
  assert.match(javascript, /data-fit-card-text="quote"/);
  assert.match(javascript, /data-fit-card-text="party"/);
  assert.match(javascript, /data-fit-card-text="name"/);
  assert.match(javascript, /function fitCardText/);
  assert.match(javascript, /function applyCardStage/);
  assert.match(javascript, /progressiveStage: "blank"/);
  assert.doesNotMatch(javascript, /reveal: stage === "portrait"/);
  assert.match(javascript, /binder-shared-card/);
  assert.match(javascript, /displayCardMarkup\(card, "binder"\)/);
  assert.match(javascript, /studio-shared-card/);
  assert.match(javascript, /function cardPresentation/);
  assert.match(javascript, /function quoteTrustLabel/);
  assert.match(javascript, /function partyTrustLabel/);
  assert.match(javascript, /function configureSourceLink/);
  assert.match(javascript, /displayCardMarkup\(card, "event"\)/);
  assert.match(javascript, /openCardDialog\(chip\.dataset\.tradeChoiceCard\)/);
  assert.match(javascript, /displayCardMarkup\(card\)/);
  assert.doesNotMatch(javascript, /displayCardMarkup\(selected, "trade"\)/);
  assert.doesNotMatch(javascript, /\["binder", "trade", "peek"\]/);
  assert.match(javascript, /quote: \{ low: 0\.024, high: 0\.058, floor: compact \? 6 : 7, ceiling: compact \? 13 : 20 \}/);
  assert.match(javascript, /while \(size > hardMin && !fitsAt\(size\)\) size -= 0\.25/);
  assert.match(javascript, /const slop = role === "quote" \? 0 : 1/);
  assert.doesNotMatch(javascript, /JNT-M01-Q01/);
  assert.match(javascript, /const presentation = cardPresentation\(card/);
  assert.equal((javascript.match(/class="card-face front"/g) || []).length, 1, "all surfaces must share one card renderer");
  assert.doesNotMatch(javascript, /miniCardMarkup/);
  assert.doesNotMatch(javascript, /class="mini-card"/);
  assert.doesNotMatch(javascript, /class="concept-stage"/);
  assert.match(css, /\.card-image-meta strong/);
  assert.match(css, /\.card-name-zone[^}]*background: var\(--civic\)/);
  assert.doesNotMatch(javascript, /favorite-heart/);
  assert.doesNotMatch(javascript, /card-heart-slot/);
  assert.doesNotMatch(javascript, /function syncBinderHeartTools/);
  assert.doesNotMatch(css, /\.binder-card-tools/);
  assert.match(javascript, /card-meta-mid/);
  assert.match(javascript, /card-code-tag/);
  assert.doesNotMatch(javascript, /card-slot-mark/);
  assert.doesNotMatch(javascript, /card\.type === "Quote" \? presentation\.subtitle : "",\s*presentation\.code/);
  assert.match(javascript, /frame === "fullart-v1" \? "" : `<strong aria-label=/);
  assert.match(themeCss, /card-code-tag[\s\S]{0,280}?min-width:\s*max-content/);
  assert.doesNotMatch(themeCss, /max-width:\s*64%/);
  assert.match(themeCss, /card-face\.front \.card-name-zone[\s\S]{0,220}?font-size:\s*8cqw/);
  assert.match(javascript, /isFullart && element\.dataset\.fitCardText !== "quote" && !compact/);
  assert.match(javascript, /function localDailyChallenge/);
  assert.match(javascript, /hydrateExtras\(\)\.catch/);
  assert.match(themeCss, /card-face\.front \.card-name-zone[\s\S]{0,280}?bottom:\s*28%/);
  assert.match(themeCss, /\[data-card-frame="fullart-v1"\] \.card-party-zone[\s\S]{0,200}?bottom:\s*23%/);
  assert.match(themeCss, /\[data-card-frame="fullart-v1"\] \.card-rarity-zone[\s\S]{0,200}?bottom:\s*18%/);
  assert.match(themeCss, /bottom:\s*0;\s*height:\s*17%;\s*max-height:\s*17%/);
  assert.match(javascript, /const hardMin = role === "quote" \? Math\.min\(6, scale\.floor\) : scale\.floor/);
  assert.match(themeCss, /\[data-card-frame="fullart-v1"\] \.card-image-meta strong[\s\S]{0,120}?display:\s*none/);
  assert.match(css, /\.card-party-zone::before[\s\S]{0,160}?2\.4cqw/);
  assert.doesNotMatch(css, /\.trade-choice-preview/);
  assert.doesNotMatch(themeCss, /\.trade-choice-preview/);
  assert.doesNotMatch(html, /trade-choice-preview/);
  assert.match(themeCss, /\[data-card-frame="fullart-v1"\][\s\S]{0,180}?border-radius:\s*12px/);
  assert.doesNotMatch(themeCss, /\[data-card-frame="fullart-v1"\] \.kalpi-card[\s\S]{0,220}?border-radius:\s*3\.6cqw/);
  assert.match(themeCss, /\[data-card-frame="fullart-v1"\][\s\S]{0,80}?\.card-code-tag[\s\S]{0,600}?height:\s*8cqw/);
  assert.match(themeCss, /\[data-card-frame="fullart-v1"\][\s\S]{0,80}?\.card-code-tag[\s\S]{0,700}?font-size:\s*6\.1cqw/);
  assert.doesNotMatch(themeCss, /\[data-card-frame="fullart-v1"\] \.card-slot-mark/);
  assert.doesNotMatch(themeCss, /justify-content:\s*space-evenly/);
  assert.doesNotMatch(html, /id="dialog-share"/);
  assert.match(html, /share-icon-button/);
  assert.doesNotMatch(html, /id="dialog-gift"/);
  assert.match(css, /\.binder-slot\s*\{[^}]*aspect-ratio:\s*63\s*\/\s*96/s);
  assert.doesNotMatch(javascript, /function toggleFavorite/);
  assert.doesNotMatch(javascript, /setLabels\.FAVORITES/);
  assert.doesNotMatch(javascript, /פייבוריטים/);
  assert.match(javascript, /setTimeout\(startWalkout/);
  assert.match(html, /pack-wrapper-klafi\.png/);
  assert.doesNotMatch(html, /pack-rip-seedance/);
  assert.match(javascript, /pack-wrapper-klafi\.png/);
  assert.doesNotMatch(html, /home-pack-rip/);
  assert.doesNotMatch(css, /\.pack-rip-lip/);
  assert.doesNotMatch(css, /\.home-pack-rip\.is-tearing/);
  assert.match(html, /id="open-pack"[^>]*>פתיחת קלף/);
  assert.match(html, /id="replay-tips"[^>]*>איך משחקים/);
  assert.match(html, /id="klafi-tips"/);
  assert.match(html, /id="klafi-tips-dim"/);
  assert.match(html, /id="klafi-tips-marks"/);
  assert.match(html, /אל תציגו שוב/);
  assert.match(javascript, /attachKlafiTips/);
  assert.match(tipsJs, /function attachKlafiTips/);
  assert.match(tipsJs, /klafi_tips/);
  assert.match(tipsJs, /klafi:tips/);
  assert.match(tipsJs, /klafi:page-tips/);
  assert.match(tipsJs, /PAGE_GUIDES/);
  assert.match(tipsJs, /getAnimations/);
  assert.match(tipsJs, /viewHasEnterOffset/);
  assert.match(tipsJs, /doc\.body/);
  assert.match(tipsJs, /fill-rule/);
  assert.match(css, /:not\(\.klafi-tips\) \{ position: relative; z-index: 1; \}/);
  assert.match(css, /#klafi-tips\.klafi-tips/);
  assert.match(css, /\.klafi-tips-dim \{ pointer-events: auto; z-index: 1; \}/);
  assert.match(css, /\.klafi-tips-marks \{ pointer-events: none; z-index: 2; \}/);
  assert.match(css, /\.klafi-tips-card \{ z-index: 4; \}/);
  assert.match(css, /\.klafi-tips-card \{[\s\S]*?background: #eee5d4/);
  assert.doesNotMatch(css, /\.klafi-tips-card \{[\s\S]*?background: rgba\(238, 229, 212, 0\.6\)/);
  assert.match(tipsJs, /kind === "circle"/);
  assert.match(tipsJs, /klafi-tips-dot/);
  assert.match(html, /id="run-guided-demo"[^>]*>Run six-card guided demo/);
  assert.doesNotMatch(tipsJs, /run-guided-demo/);
  assert.match(html, /id="idle-storage"/);
  assert.match(javascript, /\/api\/idle\/settle/);
  assert.match(javascript, /\/api\/idle\/seen/);
  assert.match(javascript, /function openIdleReturn/);
  assert.match(javascript, /model\.packPhase = "sealed";\s+renderPack\(\);\s+showView\("pack"\)/);
  assert.match(html, /data-nav="growth"/);
  assert.match(html, /data-nav="growth"><span aria-hidden="true">▣<\/span>/);
  assert.doesNotMatch(html, /data-nav="growth"><span aria-hidden="true">↗/);
  assert.match(javascript, /function localAchievementList/);
  assert.match(javascript, /function achievementList/);
  assert.match(javascript, /if \(model\.token\) hydrateExtras/);
  assert.match(javascript, /model\.extrasReady = true/);
  assert.doesNotMatch(javascript, /results\.every\(\(\{ status \}\) => status === "fulfilled"\)/);
  assert.match(css, /font-variant-emoji:\s*text/);
  assert.match(html, /data-nav="achievements"/);
  assert.doesNotMatch(html, /data-nav="events"/);
  assert.match(html, /data-nav="studio"/);
  assert.match(html, /Reset daily pack now/);
  assert.match(html, /id="header-debug-reset"/);
  assert.match(html, />Presentation<\/a>/);
  assert.match(html, /poc-response\/index\.html" target="_blank"/);
  assert.match(html, /Presentation Studio/);
  assert.match(html, /poc-response\/index\.html\?studio=1/);
  assert.match(html, /Run six-card guided demo/);
  assert.match(html, /id="play-studio-reveal"/);
  assert.match(html, /Expanded content studio/);
  assert.match(html, /id="delay-quote"/);
  assert.match(html, /id="studio-party-tabs"/);
  assert.match(html, /id="studio-card-grid"/);
  assert.match(html, /Copy politician · 3 images/);
  assert.match(javascript, /buildMemberWeavePrompt/);
  assert.match(javascript, /buildWeavePrompt/);
  assert.match(javascript, /data-save-studio-card/);
  assert.match(javascript, /\/api\/studio\/content/);
  assert.match(javascript, /"01 \/ 04 · quote"/);
  assert.match(javascript, /"04 \/ 04 · portrait"/);
  assert.doesNotMatch(javascript, /REVEAL_TIMING_KEY/);
  assert.match(javascript, /\/api\/bootstrap/);
  assert.match(javascript, /\/api\/home/);
  assert.match(javascript, /\/shell\.json/);
  assert.match(html, /id="home-view"[^>]*class="view active"/);
  assert.match(javascript, /HOME_CACHE_KEY/);
  assert.match(html, /boot-warmup\.js/);
  assert.doesNotMatch(warmup, /\/api\/warm/);
  assert.doesNotMatch(warmup, /\/api\/catalog/);
  assert.match(warmup, /\/api\/home/);
  assert.match(javascript, /studioKey/);
  assert.match(javascript, /x-kalpi-studio/);
  assert.match(html, /data-studio-only/);
  assert.match(html, /id="studio-release-sets"/);
  assert.match(html, /id="studio-pack-now"/);
  assert.match(javascript, /function populateReleaseSets/);
  assert.match(javascript, /function readStudioPack/);
  assert.match(javascript, /data-pack-weight/);
  assert.match(html, /האוסף שייך לקוד הזה, לא למייל/);
  assert.match(javascript, /\/api\/studio\/config/);
  assert.match(javascript, /updateStudioCardPreview/);
  assert.match(javascript, /\["quote\.displayText", "art\.artKey"\]/);
  assert.match(javascript, /\/api\/debug\/reset-pack/);
  assert.match(javascript, /\/api\/packs\/demo/);
  assert.match(javascript, /Daily state was not changed/);
  assert.match(html, /גילוי נאות/);
  assert.match(javascript, /referral_opened/);
  assert.match(javascript, /gift_preview_created/);
  assert.match(html, /id="dialog-whatsapp"/);
  assert.match(javascript, /https:\/\/wa\.me\/\?text=/);
  assert.match(html, /id="earned-badge-rail"/);
  assert.match(html, /id="open-bibi-pack"/);
  assert.doesNotMatch(html, /id="open-quiz"/);
  assert.doesNotMatch(html, /id="quiz-dialog"/);
  assert.match(javascript, /\/api\/packs\/bibi-demo/);
  assert.match(javascript, /badgeArtwork/);
  assert.doesNotMatch(javascript, /function badgeSymbol/);
  assert.match(html, /האם תגיעו לדרגת ראש הממשלה/);
  assert.match(html, /רמה 1\/5/);
  assert.match(html, /id="level-next"/);
  assert.doesNotMatch(html, /id="dialog-copies"/);
  assert.doesNotMatch(html, /id="dialog-ownership"/);
  assert.doesNotMatch(javascript, /נתון מדומה להדגמה/);
  assert.doesNotMatch(javascript, /שחקנים נוספים מחזיקים/);
  assert.match(javascript, /function displayCardMarkup/);
  assert.match(javascript, /card-copies-tag/);
  assert.match(html, /החלפות/);
  assert.match(html, /מלחמת הסיעות/);
  assert.doesNotMatch(html, /כל סדרות המיוחדים/);
  assert.match(html, /id="level-progress"/);
  assert.match(javascript, /\/api\/events\/.*\/pull/);
  assert.match(html, /id="trade-offered-set"/);
  assert.match(html, /id="trade-wanted-set"/);
  assert.match(html, /id="trade-active"/);
  assert.match(html, /id="trade-compose"/);
  assert.match(html, /id="trade-create"[\s\S]*id="trade-offered-set"/);
  assert.match(html, /id="avatar-seal"/);
  assert.match(html, /id="level-letter"/);
  assert.match(html, /id="level-letter-text"/);
  assert.match(html, /id="level-streak"/);
  assert.match(html, /id="level-streak-count"/);
  assert.match(javascript, /const showStreak = streak >= 3/);
  assert.match(javascript, /elements\.cooldownCopy\.hidden = true/);
  assert.match(css, /\.masthead \.presentation-link/);
  assert.match(html, /id="rank-names"/);
  assert.match(html, /id="numbered-sets"/);
  assert.match(html, /id="numbered-tip"/);
  assert.match(javascript, /card-numbered-tag/);
  assert.match(javascript, /card-numbered-tag[^>]*>\$\{instance\.numberedIndex\}\/\$\{instance\.numberedOf\}<\/b>/);
  assert.doesNotMatch(javascript, /<small>מקום ברשימה<\/small>/);
  assert.match(css, /#b42318/);
  assert.match(javascript, /letterChip/);
  assert.match(javascript, /letterArt/);
  assert.match(javascript, /data-letters/);
  assert.match(javascript, /card-rarity-run/);
  assert.match(javascript, /holo-chroma/);
  assert.match(css, /aspect-ratio:\s*2\s*\/\s*3/);
  assert.match(css, /holo-chroma/);
  assert.match(javascript, /function mergeLiveCatalogFields/);
  assert.match(javascript, /function streakFireMarkup/);
  assert.match(javascript, /function collectorFaceMarkup/);
  assert.match(javascript, /collector-streak[\s\S]{0,80}?streak-count/);
  assert.match(javascript, /slotLabel \|\| card\.subtitleHe/);
  assert.match(javascript, /membershipNote/);
  assert.match(javascript, /if \(live\.membershipNote\) card\.membershipNote = live\.membershipNote/);
  assert.match(css, /width:\s*11px/);
  assert.match(css, /height:\s*16\.5px/);
  assert.match(javascript, /numberedCopies/);
  assert.match(javascript, /numberedEvery/);
  assert.match(javascript, /#numbered-every/);
  assert.match(javascript, /maybeShowNumberedTip/);
  assert.match(javascript, /ממוספר/);
  assert.match(javascript, /מקום ברשימה/);
  assert.match(javascript, /streak-fire/);
  assert.match(css, /\.card-numbered-tag/);
  assert.match(css, /\.numbered-tip/);
  assert.match(css, /streak-fire/);
  assert.match(css, /holo-orbit/);
  assert.match(css, /ballot-paper\.png/);
  assert.match(html, /flame-outer/);
  assert.match(javascript, /ACTIVE_TRADE_EXISTS/);
  assert.match(javascript, /function applyTradeResult/);
  assert.match(javascript, /function refreshDailyChallenge/);
  assert.match(javascript, /function renderAvatarSeal/);
  assert.match(css, /\.avatar-seal/);
  assert.match(css, /\.trade-thumb-frame/);
  assert.match(css, /fermi-bar-rise/);
  assert.match(css, /cubic-bezier\(0\.16,\s*1,\s*0\.3,\s*1\)/);
  assert.match(javascript, /function tradeThumbMarkup/);
  assert.match(javascript, /function pollWatchedTrade/);
  assert.match(javascript, /function settleReceivedCard/);
  assert.match(html, /class="trade-thumb"/);
  assert.match(javascript, /class="trade-offer-bar"/);
  assert.match(javascript, /אין לכם את/);
  assert.match(css, /\.trade-offer-action/);
  assert.match(css, /\.trade-offer-action\.accept/);
  assert.match(javascript, /trade-offer-action accept/);
  assert.match(css, /\.challenge-hist-col b[\s\S]{0,80}?width:\s*32px/);
  assert.match(css, /\.challenge-hist-plot[\s\S]{0,160}?direction:\s*ltr/);
  assert.match(css, /\.challenge-hist-axis[\s\S]{0,160}?direction:\s*ltr/);
  assert.match(css, /\.challenge-hist-plot[\s\S]{0,160}?height:\s*188px/);
  assert.match(javascript, /TRADE_BOARD_PAGE_SIZE = 3/);
  assert.match(javascript, /function renderTradeBoard/);
  assert.match(javascript, /function tradeHasCards/);
  assert.match(javascript, /function tradeSideMarkup/);
  assert.match(javascript, /נותנים/);
  assert.match(javascript, /מקבלים/);
  assert.match(javascript, /עוד \$\{nextCount\}/);
  assert.match(html, /id="trade-board-offered"/);
  assert.match(html, /id="trade-board-wanted"/);
  assert.match(html, /id="trade-board-pager"/);
  assert.match(css, /\.trade-offer \.trade-thumb-frame[\s\S]{0,80}?width:\s*100%/);
  assert.match(css, /\.trade-offer \{[^}]*width:\s*min\(100%,\s*460px\)/);
  assert.match(javascript, /function partyDisplayName/);
  assert.match(javascript, /function partyRegister/);
  assert.match(javascript, /model\.gameConfig\?\.parties/);
  assert.match(javascript, /targetPartyNameHe/);
  assert.match(javascript, /function challengeRecap/);
  assert.match(javascript, /function renderChallengeRecap/);
  assert.match(javascript, /hasCrowd = leaders\.length >= 2/);
  assert.match(javascript, /recap\.hasCrowd \? `<div class="challenge-hist">/);
  assert.match(javascript, /collectorCrowd/);
  assert.match(html, /id="daily-challenge-recap"/);
  assert.match(html, /id="today-challenge-hook"/);
  assert.doesNotMatch(html, /id="today-event-hook"/);
  assert.match(html, /id="today-leader-hook"/);
  assert.match(html, /id="today-specials-row"/);
  assert.match(html, /class="today-specials-line"/);
  assert.match(html, /id="today-specials-copy"/);
  assert.match(html, /id="today-specials-copy-repeat"/);
  assert.match(html, /data-today-nav="specials"/);
  assert.match(html, /id="today-specials-row"[^>]*hidden/);
  assert.doesNotMatch(html, /id="today-specials-visual"/);
  assert.doesNotMatch(html, /id="today-specials-hook"/);
  assert.match(javascript, /function renderTodaySpecials/);
  assert.match(javascript, /function layoutTodaySpecials/);
  assert.match(javascript, /is-marquee/);
  assert.match(javascript, /idlePullCount \?\? previous\.idlePullCount/);
  assert.match(javascript, /achievements \?\? previous\.achievements/);
  assert.match(javascript, /function hydrateHome[\s\S]*renderAchievements/);
  assert.match(css, /specials-marquee/);
  assert.doesNotMatch(css, /\.today-specials-line\.is-ready:not\(\.is-fit\)/);
  assert.match(javascript, /function claimTodaySpecial/);
  assert.match(javascript, /model\.specialWindow/);
  assert.match(javascript, /הקלף מוכן לאיסוף/);
  assert.match(javascript, /serviceWorker\.register\("\/sw\.js"\)/);
  assert.match(javascript, /function scheduleIdleNotification/);
  assert.match(javascript, /\/api\/leagues/);
  assert.match(javascript, /function createLeagueRoom/);
  assert.match(javascript, /function joinLeagueFromInput/);
  assert.match(javascript, /הליגה נפתחה/);
  assert.match(javascript, /נכנסתם לליגה/);
  assert.match(html, /rel="manifest"/);
  assert.match(html, /manifest\.webmanifest/);
  assert.match(html, /id="enable-idle-notify"/);
  assert.match(html, /id="create-league"/);
  assert.match(html, /id="join-league"/);
  assert.match(html, /id="league-rooms"/);
  assert.match(html, /id="profile-leagues-title">ליגות/);
  assert.match(html, /שם הליגה/);
  assert.doesNotMatch(html, /id="profile-leagues-title">חדרים/);
  assert.match(html, /id="site-card-peeks"/);
  assert.match(css, /\.pack-shadow \{\s*display: none;/);
  assert.match(css, /\.site-card-peeks \{\s*display: none;/);
  assert.match(html, /id="today-challenge-visual"/);
  assert.match(html, /hero-art-knesset\.png/);
  assert.match(javascript, /function renderSiteCardPeeks/);
  assert.ok(
    html.indexOf('id="site-card-peeks"') < html.indexOf('class="masthead"'),
    "background card layer must sit behind every application surface",
  );
  assert.doesNotMatch(javascript, /לא נבחר ציטוט/);
  assert.match(javascript, /if \(!text\) return ""/);
  assert.match(html, /id="player-name"/);
  assert.match(html, /id="profile-dialog"/);
  assert.match(html, /id="profile-recovery-code"/);
  assert.match(html, /id="profile-restore-input"/);
  assert.match(html, /id="copy-recovery-code"/);
  assert.match(html, /id="restore-recovery-code"/);
  assert.match(html, /האוסף שייך לקוד הזה/);
  assert.match(javascript, /function restoreSessionFromCode/);
  assert.match(javascript, /function copyRecoveryCode/);
  assert.match(javascript, /SESSION_TOKEN_PATTERN/);
  assert.match(javascript, /\[0-9a-f\]\{8\}-\[0-9a-f\]\{4\}-\[0-9a-f\]\{4\}-\[0-9a-f\]\{4\}-\[0-9a-f\]\{12\}/);
  assert.doesNotMatch(javascript, /data-report-trade/);
  assert.match(javascript, /data-report-name/);
  assert.doesNotMatch(javascript, /function openTradeReport/);
  assert.match(javascript, /function openNameReport/);
  assert.match(html, /value="name"/);
  assert.doesNotMatch(html, /value="trade"/);
  assert.match(javascript, /\/api\/profile/);
  assert.match(html, /id="shared-view"/);
  assert.match(html, /id="shared-trust"/);
  assert.match(html, /id="open-trust-legend"/);
  assert.match(html, /home-title-row/);
  assert.match(html, /id="trust-dialog"/);
  assert.match(html, /id="dialog-trust"/);
  assert.match(javascript, /function showSharedCard/);
  assert.match(javascript, /function isLookOnlyShowcase/);
  assert.match(javascript, /function bootstrapShowcase/);
  assert.match(javascript, /function renderShowcaseBinder/);
  assert.match(javascript, /model.binderFilter !== "NUMBERED"/);
  assert.match(javascript, /function catalogCardMarkup/);
  assert.match(javascript, /\/share\/binder/);
  assert.match(binderShare, /showcase=1/);
  assert.match(binderShare, /אין כאן שחקן/);
  assert.match(javascript, /get\("showcase"\) === "1"/);
  assert.match(html, /id="showcase-view"/);
  assert.match(html, /id="showcase-grid"/);
  assert.match(html, /id="studio-share-binder"/);
  assert.match(html, /id="studio-share-binder-link"/);
  assert.match(html, /id="dialog-holders"/);
  assert.doesNotMatch(javascript, /card-holders-chip/);
  assert.match(html, /אין כאן שחקן במשחק/);
  assert.match(javascript, /\/api\/card-holders/);
  assert.match(javascript, /function holderLine/);
  assert.match(javascript, /function printRunFor/);
  assert.match(javascript, /function filterSetChip/);
  assert.match(javascript, /function prefetchBinderArt/);
  assert.match(javascript, /FILTER_SET_SHORT/);
  assert.match(javascript, /loading="lazy"/);
  assert.match(css, /animation-duration: 3\.8s/);
  assert.match(warmup, /design-assets/);
  assert.match(javascript, /function possibleNumberedCards/);
  assert.match(javascript, /function isPossibleNumberedCard/);
  assert.match(javascript, /שחקנים מחזיקים בקלף הזה/);
  assert.match(javascript, /\$\{count\}\/\$\{of\} מחזיקים עותק ממוספר/);
  assert.match(warmup, /lookOnlyShowcase/);
  assert.match(warmup, /\/share\/binder/);
  assert.doesNotMatch(javascript, /שחקנים נוספים מחזיקים/);
  assert.match(javascript, /תצוגת שיתוף בלבד/);
  assert.match(javascript, /הקלף לא נוסף לאוסף שלכם/);
  assert.match(javascript, /גלו עוד \$\{progression\.remaining\} קלפים חדשים כדי להתקדם לרמה הבאה/);
  assert.match(html, /data-today-nav="growth"/);
  assert.doesNotMatch(html, /data-today-nav="events"/);
  assert.match(javascript, /data-trade-card/);
  assert.match(javascript, /openCardDialog\(card\.dataset\.tradeCard\)/);
  assert.match(css, /\.app-shell\.home-active \.level-strip/);
  assert.match(css, /grid-template-areas: "identity progress"/);
  assert.match(css, /grid-template-columns: minmax\(132px, auto\) minmax\(0, 1fr\)/);
  assert.match(css, /\.level-pack-icon \{ display: none/);
  assert.match(html, /class="level-reward-pack"/);
  assert.match(css, /\.level-strip[^}]*direction: rtl/);
  assert.match(css, /\.policy-dialog ol \{ padding-inline-start:/);
  assert.match(css, /\.bottom-nav button[^}]*border-inline-start:/);
  assert.match(css, /html,\s*body\s*\{[^}]*height: 100%[^}]*overflow: hidden/s);
  assert.match(css, /\.top-nav-row\s*\{[^}]*position: fixed/s);
  assert.doesNotMatch(javascript, /window\.scrollTo/);
  assert.match(html, /id="binder-pager"/);
  assert.match(html, /סינון האוסף לפי סדרה או מפלגה/);
  assert.match(javascript, /binderParty: ""/);
  assert.match(javascript, /data-binder-party/);
  assert.match(javascript, /בחירת מפלגה או הכול/);
  assert.match(javascript, /const setOrder = \["ALL", \.\.\.releaseOrder\.map/);
  assert.match(javascript, /const partyOk = !model\.binderParty \|\| card\.set === model\.binderParty/);
  assert.match(javascript, /model\.binderParty = select\.value/);
  assert.match(css, /\.filter-party/);
  assert.match(css, /\.filter-sets/);
  assert.match(html, /id="community-tabs"/);
  assert.match(html, /role="tabpanel"/);
  assert.match(html, /aria-controls="community-panel-trade"/);
  assert.match(html, /aria-current="page"/);
  assert.match(javascript, /function moveTabFocus/);
  assert.match(javascript, /button\.tabIndex = active \? 0 : -1/);
  assert.doesNotMatch(javascript, /collection-star-count" role="button"/);
  assert.doesNotMatch(javascript, /badge-medallion" role="button"/);
  assert.doesNotMatch(javascript, /textAlign = "left"/);
  assert.match(css, /4\.2cqw/);
  assert.doesNotMatch(css, /4\.2vw/);
  assert.match(javascript, /cardTitle/);
  assert.match(javascript, /cardCode/);
  assert.match(html, /card-surface-40/);
  assert.doesNotMatch(html, /id="home-pack-rip"/);
  assert.match(javascript, /function catalogReady/);
  assert.match(javascript, /function loadStaticCatalog/);
  assert.match(javascript, /function hydrateExtras/);
  assert.match(javascript, /Promise\.all\(jobs\.map/);
  assert.doesNotMatch(javascript, /scheduleExtrasPrefetch/);
  assert.doesNotMatch(javascript, /extrasPrefetchTimer/);
  assert.match(javascript, /\/catalog\.json/);
  assert.match(javascript, /cache: "force-cache"/);
  assert.match(javascript, /const warmedShell = window\.__kalpiWarmup\?\.shell/);
  assert.match(javascript, /const warmedCatalog = window\.__kalpiWarmup\?\.catalog/);
  assert.match(javascript, /const warmedHome = window\.__kalpiWarmup\?\.home/);
  assert.match(javascript, /window\.__kalpiWarmup\?\.holders/);
  assert.match(warmup, /\/api\/card-holders/);
  assert.match(javascript, /hydrateCardHolders\(\)\.catch/);
  assert.match(javascript, /const due = !timeUntil\(model\.serverState\?\.nextIdleAt\)/);
  assert.match(javascript, /jobs\.push\(\["events", \(\) => request\("\/api\/events"\)\]\)/);
  assert.match(javascript, /request\("\/api\/community"\)/);
  assert.match(javascript, /LIVE_RELEASE_SET_IDS/);
  assert.match(javascript, /function playerCatalog/);
  assert.match(javascript, /function artUrl/);
  assert.match(javascript, /function prefetchCardArt/);
  assert.match(javascript, /<img class="\$\{className\}" src="\$\{url\}"/);
  assert.match(css, /img\.card-art/);
  assert.match(javascript, /const playerCards = playerCatalog\(\)/);
  assert.doesNotMatch(javascript, /playerCatalog\(\)\.filter\(\(card\) =>\s*card\.idleEligible/);
  assert.match(javascript, /function localStarCount/);
  assert.match(javascript, /visible-sets-2/);
  assert.doesNotMatch(javascript, /\["state", \(\) => request\("\/api\/state"\)\]/);
  assert.doesNotMatch(javascript, /\["trades", \(\) => request\("\/api\/trades"\)\]/);
  assert.doesNotMatch(javascript, /\["leaderboards", \(\) => request\("\/api\/leaderboards"\)\]/);
  assert.doesNotMatch(javascript, /\["activity", \(\) => request\("\/api\/activity"\)\]/);
  assert.match(javascript, /hydrateExtras\(\)\.catch/);
  assert.match(javascript, /טוענים את האלבום/);
  assert.match(javascript, /searchParams\.set\("view"/);
  assert.match(javascript, /function nextCachedIdleCard/);
  assert.match(javascript, /function cachedDueCount/);
  assert.match(javascript, /function hydrateIdleQueue/);
  assert.match(javascript, /function scheduleIdleRefill/);
  assert.match(javascript, /function flushPendingIdleSeen/);
  assert.match(javascript, /PENDING_IDLE_SEEN_KEY/);
  assert.match(javascript, /function flushPendingReports/);
  assert.match(javascript, /PENDING_REPORTS_KEY/);
  assert.match(javascript, /x-idempotency-key/);
  assert.match(javascript, /cachedDueCount\(\) > 1 \? "backlog"/);
  assert.match(javascript, /cachedBufferSize < \(model\.serverState\?\.idleCapacity \|\| 8\)/);
  assert.match(javascript, /const hasMaterializedCard = model\.idleQueue\.length > 0/);
  assert.match(javascript, /playHomePackRip\(\{ holdAtEnd: !cached \}\)/);
  assert.match(javascript, /await rip\.finished/);
  assert.match(javascript, /if \(!model\.token\) await hydrateHome\(\)/);
  assert.match(warmup, /\/catalog\.json/);
  assert.match(warmup, /\/shell\.json/);
  assert.match(warmup, /window\.__kalpiWarmup/);
  assert.match(warmup, /cache: "force-cache"/);
  assert.match(warmup, /Math\.random\(\) \* 8000/);
  assert.doesNotMatch(warmup, /\/api\/warm/);
  assert.match(css, /\.binder-slot\.is-loading/);
  assert.match(css, /binder-well-wait/);
  assert.match(html, /id="achievements-empty"/);
  assert.match(html, /id="growth-empty"/);
  assert.doesNotMatch(html, /id="quiz-fail"/);
  assert.match(html, /id="level-unlocks"/);
  assert.match(html, /id="open-pending-level"/);
  assert.match(javascript, /klafi-seen-level-dialog/);
  assert.doesNotMatch(javascript, /pendingRewards\?\.length \|\|/);
  assert.doesNotMatch(html, /שעון ירושלים/);
  assert.match(html, /theme-pack-v2\.css/);
  assert.match(html, /card-surface-40/);
  assert.match(html, /id="report-dialog"/);
  assert.match(html, /דיווח על טעות בקלף/);
  assert.match(html, /id="studio-report-list"/);
  assert.match(javascript, /function hydrateStudioReports/);
  assert.match(javascript, /function applyStudioAccess/);
  assert.match(javascript, /\/api\/studio\/reports/);
  assert.match(themeCss, /\.card-dialog \.kalpi-card[^}]*width:\s*min\(var\(--card-width\),\s*100%\)/s);
  assert.match(css, /--card-width:\s*min\(330px,\s*calc\(100vw - 42px\)\)/);
  assert.doesNotMatch(css, /\.kalpi-card \{ width: 276px; \}/);
  assert.doesNotMatch(css, /walkout \.kalpi-card \{ width: min\(270px/);
  assert.doesNotMatch(css, /walkout \.kalpi-card \{ width: min\(235px/);
  assert.match(themeCss, /\.new-stamp[^}]*top:\s*50%[^}]*translateY\(-50%\)/s);
  assert.doesNotMatch(themeCss, /#pack-view \.walkout-receipt\s*\{\s*display:\s*none/);
  assert.match(javascript, /הציטוט קוצר/);
  assert.match(javascript, /ממתינה לבדיקת ועדת הבחירות/);
  assert.match(html, /data-theme="pack-v2"/);
  assert.match(html, /id="visual-theme"/);
  assert.match(html, /id="visual-card-frame"/);
  assert.match(html, /id="visual-density"/);
  assert.match(html, /id="visual-quote-reveal"/);
  assert.match(html, /id="dialog-instagram"/);
  assert.match(html, /data-debug-only/);
  assert.match(javascript, /function applyVisualConfig/);
  assert.match(javascript, /function shareToInstagram/);
  assert.match(javascript, /function makeStoryImage/);
  assert.match(javascript, /function makeWhatsAppImage/);
  assert.match(javascript, /תראו מה שלפתי בקְלָפִי!/);
  assert.match(javascript, /function paintShareCardFace/);
  assert.match(javascript, /function paintFullartShareIdentity/);
  assert.match(javascript, /SHARE_PULL_LINE/);
  assert.match(css, /#card-dialog \.dialog-close/);
  assert.match(css, /#card-dialog \.dialog-close:focus-visible/);
  assert.doesNotMatch(css, /#card-dialog \.dialog-close:focus-visible[^}]*var\(--foil\)/);
  assert.match(javascript, /\/share\/\$\{encodeURIComponent\(cardId\)\}/);
  assert.match(html, /id="share-sheet"/);
  assert.doesNotMatch(html, /id="binder-flip-frame"/);
  assert.doesNotMatch(javascript, /function toggleBinderCardFrame/);
  assert.match(javascript, /function prefetchAvatars/);
  assert.match(javascript, /function localAchievementMeasures/);
  assert.match(html, /id="home-enable-notify"/);
  assert.match(html, /data-replay-tips/);
  assert.match(javascript, /data-binder-owned/);
  assert.match(javascript, /binderOwnedOnly/);
  assert.match(html, /fullart-v1/);
  assert.match(javascript, /card-identity-stack/);
  assert.match(javascript, /card-rarity-zone/);
  assert.match(css, /data-card-frame="fullart-v1"/);
  assert.match(themeCss, /#app \.kalpi-card\[data-card-frame="fullart-v1"\]/);
  assert.match(css, /dialog-meta-row/);
  assert.match(javascript, /\/api\/trades\/\$\{encodeURIComponent\(tradeId\)\}\/cancel/);
  assert.match(javascript, /new ResizeObserver/);
  assert.match(javascript, /data-card-surface/);
  assert.match(themeCss, /aspect-ratio: 63 \/ 96/);
  assert.match(css, /data-quote-reveal="ink-v2"/);
  assert.match(css, /pack-quote-ink/);
  assert.doesNotMatch(javascript, /floor: 4\.5/);
  assert.doesNotMatch(html, /id="dialog-flip"/);

  const studioStart = html.indexOf('<section id="studio-view"');
  const errorStart = html.indexOf('<section id="error-view"');
  const playerHtml = `${html.slice(0, studioStart)}${html.slice(errorStart)}`;
  const playerText = playerHtml.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ");
  assert.doesNotMatch(playerText, /שלב/);
  assert.doesNotMatch(playerText, /\b(?:Today|Binder|Growth|Achievements|Events|Creator|Copy|Close|Something|Try|cards|Source)\b/);
  for (const staleCopy of ["Why it matters", "Open today’s pack", "Share this pull", "Trade preview"]) {
    assert.doesNotMatch(javascript, new RegExp(staleCopy, "i"));
  }
});
